### ISSUE TITLE
Task comment should notify people

### ISSUE THREAD

**Issue by rafaeljusto** [Teamwork/github-sync#23]
**Describe the bug**
The comment added to the task doesn't notify people. It would be great if we could notify the same people from the last comment or the people that are following the task comments.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a task, add some people as comment followers
2. Create a PR and reference the task
3. Check the task comment notifications

**Expected behaviour**
Those people following the task comments to be notified.

**Additional context**
Nobody is notified.

**Comment by joesken** [comment]
My two cents - would be good to have this as an option with the ability to turn it on and off (I know I personally don't want to get notified via TW of every PR merged etc).

**Comment by rafaeljusto** [comment]
AFAIK this plugin is stateless, so maybe we would need a special syntax in the link regexp.

e.g. `http://example.teamwork.com/#/tasks/123 !notify`

The downside is adding special keywords only for the action. 🤔 I could survive without these notifications if that means adding hacks to this action.

**Comment by miguelbemartin** [comment]
I see the benefit to get notified via TW if any comment is added by this action. The user can "unfollow" the task if they are not interested in being notified anymore.

**Comment by joesken** [comment]
I *do* want to see comments / updates by people though (just not every PR which chances are I may also getting notified by from GitHub anyway).   I suppose it is maybe different roles. Mine is more overview/supervisory hence where I'm coming from on it.

**Comment by miguelbemartin** [comment]
@joesken Yeah, I get your point. How does your workflow look like? Do you assign more than one PR to the same task? Do you think it could be interesting as a manager to receive a notification when the PR is approved or merged?

**Comment by joesken** [comment]
Hi @miguelbemartin yes I think 'merged' is probably a notification worth seeing as it is advancing the code/task.  On the whole now, we don't have multiple PRs per task but it does happen (we are also still figuring out the optimal workflow so it is shifting sands). Anything else I can shed any light on don't hesitate, thanks.

**Comment by miguelbemartin** [comment]
I found another problem with the current approach. After the message created by Github Actions, if the user adds another comment to the task, the list of people who should be notified is lost. 

PR #24 will fix this problem.

**Comment by miguelbemartin** [comment]
I will merge the PR into master! 

@joesken I hope you are happy with that as well! Thanks for the feedback.
