### ISSUE TITLE
Messages does not distinguish if a closed PR was merged or not.

### ISSUE THREAD

**Issue by toffentoffen** [Teamwork/github-sync#25]
**Describe the bug**
If a PR is closed without merging the added message to task says "merged":
> toffentoffen merged a PR: conversion reports refactor for stages

**To Reproduce**
1. Close a PR without merging.

**Expected behavior**
Message should be:
toffentoffen closed a PR without merging: conversion reports refactor for stages

**Additional context**

**Comment by miguelbemartin** [comment]
Nice catch @toffentoffen ;) Thanks for taking the time to open an issue and a PR.
