### ISSUE TITLE
Delete markdown comments 

### ISSUE THREAD

**Issue by miralize** [Teamwork/github-sync#38]
**Describe the bug**
Not sure if this is on teamwork or this addons end, but seeing markdown comments come through as part of the Teamwork comment

**To Reproduce**
1. Create a PR with a markdown comment `<!-- Test comment -->`
4. Test comment rendered as a string in Teamwork comment 
> `<!-- Test comment -->`

**Expected behavior**
That markdown comments would not be rendered

**Comment by Flexicon** [comment]
Hey, what's a real use-case for adding markdown comments to a PR that you **don't want** to be published to TW?

Just looking for context here 🤔

**Comment by miralize** [comment]
In a lot of PR templates theres often comments like 

>`<!-- Add a link to the task -->`

or 

> `<!-- Add a  description -->`

I dont think thats really valuable in being rendered in Teamwork, curious as to what you think?

**Comment by Flexicon** [comment]
Ah right fair play. I just saw it there in the PR template for this repo as well. I wasn't aware that that was a feature of Github flavour markdown but yeah I agree. No real value there.

I think that's a thing for the projects Markdown renderer at this point though, unless we use sed or awk to strip out those comments before sending. Might be more trouble than it's worth though at that point.

**Comment by miralize** [comment]
Happy to close if you think so then 👍

**Comment by Flexicon** [comment]
Yeah I think this should be closed cause from reading [this](https://stackoverflow.com/a/20885980/3112167) it looks like those html style comments are a part of standard markdown but just something github allows.

That said, there is a hacky approach to making Markdown "comments" that pretty much any markdown renderer will respect (including the one projects uses, see below) and it is mentioned in that StackOverflow thread too.

markdown | rendered
--- | ---
![image](https://user-images.githubusercontent.com/5813378/128351674-019ba1c7-e18c-4203-b0ea-2e5926b7208a.png) | ![image](https://user-images.githubusercontent.com/5813378/128351720-59b3e7f8-6af6-4730-8a6e-e75922875ac7.png)

**Comment by miralize** [comment]
does that work in gh flavour markdown 🤔 ?

**Comment by Flexicon** [comment]
Yep

[//]: <> (This is also a comment.)

☝️ 

<img width="421" alt="Screenshot 2021-08-05 at 15 46 26" src="https://user-images.githubusercontent.com/5813378/128360687-8c5d8eae-ba76-4cca-a1ac-b22edf3cd887.png">

**Comment by Flexicon** [comment]
Again, that's because it's part of the standard markdown syntax, not anything fancy. Just "abusing" link/image labels.
