### ISSUE TITLE
Incorrect URL in ReadMe for 'API token guide'

### ISSUE THREAD

**Issue by dducrest** [Teamwork/github-sync#54]
**Describe the bug**
I think that you have an old url in the ReadMe 

* `TEAMWORK_API_TOKEN`: The API token to authenticate the workflow. Follow [this guide](https://developer.teamwork.com/guides/api-key-url/) to find your URL and API key.

**To Reproduce**
1. Open [ReadMe](https://github.com/Teamwork/github-sync/blob/master/README.md)
2. Locate link 'this guide' in [Prerequisites](https://github.com/Teamwork/github-sync/blob/master/README.md#prerequisites) section.
3. Click 'this guide'
4. Notice 404 page message
![image](https://user-images.githubusercontent.com/2745258/148973524-2eeb2e5a-8431-478e-95af-603d4babf20a.png)

**Expected behavior**
I think that you want to link to: https://developer.teamwork.com/projects/apikey/key

**Comment by willbush** [comment]
I think this might be a better link: https://support.teamwork.com/projects/using-teamwork/locating-your-api-key
