### ISSUE TITLE
Differentiate between a closed PR and a merged one

### ISSUE THREAD

**Issue by shanepm** [Teamwork/github-sync#9]
Small one, but I just saw it says `X closed a PR` when the PR is merged. Is it possible to say `X merged a PR` in that case?

**Comment by miguelbemartin** [comment]
Thanks for the feedback @shanepm

**Comment by rasoulnouri78** [comment]
> name: teamwork
> 
> on: pull_request: types: [opened, closed] pull_request_review: types: [submitted]
> 
> jobs: teamwork-sync: runs-on: ubuntu-latest name: Teamwork Sync steps: - uses: teamwork/github-sync@master with: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} TEAMWORK_URI: ${{ secrets.TEAMWORK_URI }} TEAMWORK_API_TOKEN: ${{ secrets.TEAMWORK_API_TOKEN }} AUTOMATIC_TAGGING: false BOARD_COLUMN_OPENED: 'PR Open' BOARD_COLUMN_MERGED: 'Ready to Test' BOARD_COLUMN_CLOSED: 'Rejected' env: IGNORE_PROJECT_IDS: '1 2 3'

@rasoulnouri78
